export const FETCH_LANES_START = 'FETCH_LANES_START'
export const FETCH_LANES_SUCCESS = 'FETCH_LANES_SUCCESS'
export const FETCH_LANES_FAILURE = 'FETCH_LANES_FAILURE'

export const FETCH_STORIES = 'FETCH_STORIES'
export const FETCH_STORIES_SUCCESS = 'FETCH_STORIES_SUCCESS'
export const FETCH_STORIES_FAILURE = 'FETCH_STORIES_FAILURE'

export const LANE_ADDED = 'LANE_ADDED'
export const LANE_DELETED = 'LANE_DELETED'
export const ENABLE_LANE_EDIT = 'ENABLE_LANE_EDIT'
export const FINISH_LANE_EDIT = 'FINISH_LANE_EDIT'
export const STORY_DROPPED = 'STORY_DROPPED'

export const STORY_ADDED = 'STORY_ADDED'
